# Generated by Django 5.1.4 on 2025-01-15 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_payment_speciality_remove_patient_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
