# Generated by Django 5.1.4 on 2025-01-15 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_visit_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
