# Generated by Django 5.1.4 on 2025-01-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_visit_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='reason',
            new_name='diagnose',
        ),
    ]
