# Generated by Django 5.1.4 on 2025-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_rename_reason_visit_diagnose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='diagnose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
