# Generated by Django 5.1.4 on 2024-12-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='is_fully_paid',
        ),
    ]
