# Generated by Django 5.1.4 on 2025-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_visit_diagnose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='diagnose',
        ),
        migrations.AddField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
