# Generated by Django 5.1.4 on 2024-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_remove_visit_amount_paid_remove_visit_is_fully_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачено'), ('paid', 'Оплачено')], default='not_paid', max_length=20),
        ),
    ]
