# Generated by Django 5.1.4 on 2024-12-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_visit_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='payment_status',
        ),
    ]
